// Field labels for the R&D record page, taken from the forms the submitter
// actually fills in.
//
// Without these, the record page falls back to humanizing the Firestore key -
// which invents names a reviewer has never seen: "Sdg Goals" for what the form
// calls "SDG Mapped", "Issn Number" for "ISSN Number", "Month Year Of
// Publication" for "Month & Year of Publication". R&D has to check a submission
// against the same field the submitter filled in, so the two screens must agree
// word for word.
//
// Extracted mechanically from each module's own form component (the <Label> next
// to the control that writes each key), so they started out identical rather
// than re-typed. Keys absent here still fall back to humanize(), so a newly
// added field shows up immediately - just under its generic name until it's
// added here too.
//
// Keyed by module slug because the same key can be labelled differently per
// module (e.g. `title`).

export const RESEARCH_FIELD_LABELS: Record<string, Record<string, string>> = {
  "publications": {
    authors: "Authors",
    bookName: "Name of the Book",
    citeAs: "Cite the paper as",
    conferenceName: "Name of the Conference",
    doi: "DoI",
    hasIndustryCollaboration: "Any Industry Collaboration?",
    hasInternationalCollaboration: "Any International Collaboration?",
    indexedIn: "Indexed",
    isbnNumber: "ISBN Number",
    isExtensionOfConference: "Is this extension of Conference?",
    isPublisherInRnDPolicyAnnexure: "Is the Publisher listed in the R&D policy Annexure?",
    impactFactor: "Impact Factor",
    issnNumber: "ISSN Number",
    journalName: "Name of the Journal",
    monthYearOfIndex: "Month & Year of Index",
    monthYearOfPublication: "Month & Year of Publication",
    organizedBy: "Organized By",
    providedBookLink: "Provide link of the Book",
    publishedPaperLink: "Published Paper Link",
    quartile: "Quartile",
    publisherName: "Name of the Publisher",
    researchDomain: "Research Domain",
    scopusOrWosLink: "Scopus/WoS Link of the Paper",
    sdgGoals: "SDG Mapped",
    title: "Title of the Paper",
    type: "Type of Publication",
  },
  "research-profiles": {
    googleScholarId: "Google Scholar ID",
    irinsProfile: "IRINS Profile",
    orcidId: "ORCID iD",
    researcherId: "Researcher ID",
    scopusAuthorId: "Scopus Author ID",
  },
  "citation-metrics": {
    citationsExcludingSelf: "No. of Citations Excluding Self Citations",
    citationsHIndex: "H-Index",
    citationsHIndexExcludingSelf: "H-Index (Excl. Self Citations)",
    citationsTotal: "Total No. of Citations",
    hIndex: "H-Index",
    hIndexExcludingSelf: "H-Index (Excluding Self Citations)",
    totalCitations: "Total No. of Citations",
  },
  "consultancy-projects": {
    amountReceived: "Amount Received (Rs.)",
    amountReceivedDate: "Date of Amount Received",
    clientName: "Client / Organization",
    clientType: "Client Type",
    consultancyAmount: "Consultancy Amount (Rs.)",
    consultancyCategory: "Consultancy Category",
    department: "Department",
    durationMonths: "Duration (Months)",
    endDate: "End Date",
    facultyConsultantsCount: "No. of Faculty Consultant(s)",
    facultyConsultantsNames: "Faculty Consultant(s)",
    facultyShare: "Faculty Share (Rs.)",
    hoursSpentDuringAcademicHours: "Hours Spent during Academic Hours",
    institutionalInfrastructureUsage: "Institutional Infrastructure Usage",
    institutionalShare: "Institutional Share (Rs.)",
    problemStatement: "Problem Statement",
    startDate: "Start Date",
    title: "Title",
  },
  "seed-funding": {
    dateOfStart: "Date of Start",
    dateSanctioned: "Date of Project Sanctioned",
    durationMonths: "Duration (Months)",
    equipmentProcured: "Equipment Procured",
    externalFundedProposalsApplied: "No. of External Funded Proposals Applied",
    financialYearOfStart: "F.Y. of Start",
    name: "Name of Student",
    nonRecurringAmount: "Non-Recurring (Rs.)",
    objectives: "Objectives of the Project",
    outcomes: "Outcomes",
    papersPublished: "Papers Published",
    patents: "Patents Filed/Published/Granted",
    piDepartment: "Dept. of PI",
    piName: "PI",
    projectStatus: "Status",
    recurringAmount: "Recurring (Rs.)",
    regdNumber: "Regd. Number",
    studentsInvolvedCount: "No. of Students Involved",
    studentsProjectsPG: "PG",
    studentsProjectsPhD: "Ph.D.",
    studentsProjectsUG: "Students Projects Executed - UG",
    studentsTrainedCount: "Students Trained",
    tentativeOutcomes: "Tentative Outcomes of Project",
    title: "Title",
    totalAmountSanctioned: "Total Amount Sanctioned (Rs.)",
    yearOfStudy: "Year of Study",
  },
  "sponsored-projects": {
    affiliation: "Affiliation of Co-PI",
    agencyName: "Agency",
    amountApplied: "Amount Applied (Rs.)",
    applicationNumber: "Application No.",
    coPiCount: "No. of Co-PI's",
    dateOfCompletion: "Date of Completion",
    dateOfStart: "Date of Start",
    dateOfSubmission: "Date of Submission",
    dateProjectSanctioned: "Date of Project Sanctioned",
    dateProposalSubmitted: "Date of Proposal Submitted",
    department: "Dept of Co-PI",
    durationMonths: "Duration (Months)",
    extendedToSeedFund: "Is the Proposal Extended to Seed Fund",
    financialYearOfCompletion: "F.Y. of Completion",
    financialYearOfStart: "F.Y. of Start",
    instituteContributionReceived: "Institute Contribution (Rs.)",
    instituteContributionSanctioned: "Institute Contribution (Rs.)",
    name: "Name of Co-PI",
    nonRecurringAmountReceived: "Non-Recurring (Rs.)",
    nonRecurringAmountSanctioned: "Non-Recurring (Rs.)",
    noOfYears: "No. of Years (e.g. First Year)",
    objectives: "Objectives of the Project",
    outcomes: "Outcomes",
    papersPublishedCitations: "No. of Papers Published (Citation Format)",
    personsTrainedCount: "No. of Persons Trained",
    piAffiliation: "Affiliation of PI",
    piDepartment: "Dept. of PI",
    piName: "PI",
    projectStatus: "Status",
    projectType: "Type of Project",
    recurringAmountReceived: "Recurring (Rs.)",
    recurringAmountSanctioned: "Recurring (Rs.)",
    sanctionedStatus: "Ongoing / Completed",
    schemeName: "Scheme",
    studentsProjectsPG: "PG",
    studentsProjectsPhD: "Ph.D.",
    studentsProjectsUG: "Students Projects Executed - UG",
    studentsTrainedCount: "No. of Students Trained",
    submittedRequiredDocs: "Submitted All Required Documents to Sponsoring Agency",
    technicalStaffTrainedCount: "No. of Technical Staff Trained",
    tentativeOutcomes: "Tentative Outcomes of Project",
    title: "Title",
    totalAmountReceived: "Total Amount (Rs.)",
    totalAmountSanctioned: "Amount Sanctioned (Rs.)",
  },
  "discovery-innovation": {
    affiliation: "Affiliation",
    applicationNumber: "Application Number",
    commercializationDate: "Commercialization Date",
    commercializationStatus: "Commercialization Status",
    commercializationType: "Type of Commercialization",
    commercializationValue: "Commercialization Value (Rs.)",
    country: "Country",
    dateGranted: "Date of Granted",
    dateOfFiling: "Date of Filing",
    datePublished: "Date of Published",
    iprStatus: "Status",
    iprType: "Type of IPR",
    isCommercialized: "Commercialized",
    isStudentPatent: "Student Patent",
    licenseePartner: "Licensee / Industry Partner",
    revenueGenerated: "Revenue Generated (Rs.)",
    sdgGoals: "SDGs Mapped",
    state: "State",
    title: "Title",
  },
  "phd-supervision": {
    awardDetails: "Details of Award",
    awardName: "Name of the Award",
    awardNature: "Nature of Award",
    awardsReceived: "Awards Received by Scholar",
    awardType: "Type of Award",
    dateOfAward: "Date of Award",
    degreeAwarded: "Degree Awarded",
    fellowshipAmount: "Amount Received (Rs.)",
    fellowshipName: "Name of Fellowship",
    fellowshipReceived: "Any Fellowship Received",
    fellowshipType: "Type of Fellowship",
    guideStatus: "Status of Guide",
    otherUniversityName: "Mention the University",
    recognizedSupervisor: "Recognized Supervisor",
    scholarAffiliation: "Affiliation of Scholar",
    scholarDepartment: "Department",
    scholarName: "Name of the Scholar",
    scholarPhone: "Phone Number of Scholar",
    yearOfAllocation: "Year of Allocation",
    yearsCompleted: "Years Completed",
  },
  "research-services": {
    academicYear: "A.Y.",
    affiliation: "Affiliation of Resource Person",
    amountReceived: "Amount Received (Rs.)",
    amountSanctioned: "Amount Sanctioned (Rs.)",
    committeeMembersCount: "No. of Organizing Committee Members",
    convenersCount: "No. of Convener / Coordinators",
    department: "Dept. of Faculty",
    editorialRole: "Editorial Role",
    editorIndexedIn: "Indexed In",
    editorIssnIsbn: "ISSN / ISBN",
    editorPapersChaptersHandled: "Number of Papers / Chapters Handled",
    editorPublicationName: "Name of the Publication",
    editorPublicationType: "Publication Type",
    editorPublicationUrl: "Publication URL",
    editorPublisher: "Publisher",
    editorPublisherOther: "Mention Publisher Name",
    editorRemarks: "Remarks",
    editorResponsibilities: "Editorial Responsibilities",
    editorScope: "National / International",
    endDate: "End Date",
    eventNature: "Nature of Workshop",
    eventType: "Event Type",
    expenditureMade: "Expenditure Made (Rs.)",
    fundNature: "Nature of Fund",
    name: "Name of the Faculty",
    noOfDays: "No. of Days",
    organized: "Organized Research Workshop",
    papersAccepted: "No. of Papers Accepted",
    papersAttendedExternal: "Papers Attended - External",
    papersAttendedInternal: "Papers Attended - Internal",
    papersIndexedCount: "No. of Papers Indexed",
    papersPublishedCount: "No. of Papers Published",
    papersReceived: "No. of Papers Received",
    participantsRegisteredExternal: "Participants Registered - External",
    participantsRegisteredInternal: "Participants Registered - Internal",
    resourcePersonsCount: "No. of Resource Person/Keynote Speakers/Session Chairs",
    reviewerPaperTitle: "Title of the Paper Reviewed",
    reviewerPublicationName: "Journal/Conference",
    reviewerPublisherName: "Publisher Name",
    reviewerReviewDate: "Review Date",
    reviewerType: "Reviewer Type",
    serviceType: "Type of Contribution",
    startDate: "Dates",
    type: "Type",
  },
  "hackathons": {
    academicYear: "A.Y.",
    affiliation: "Affiliation of the Evaluator",
    departmentOrCell: "Department/Cell",
    designation: "Designation",
    durationHours: "Duration (Hrs)",
    endDate: "End Date",
    eventTitle: "Event Title",
    eventType: "Event Type",
    ideasPresentedCount: "Ideas Presented",
    ideasUploadedYukti: "Ideas Uploaded in YUKTI",
    ideasVerifiedRecommendedYukti: "Ideas Verified & Recommended",
    levelOfEvent: "Level of Event",
    name: "Name of the Evaluator",
    noOfProblemStatements: "No. of Problem Statements",
    organizingDeptCell: "Organizing Department / Cell",
    participantsExternal: "Participants - External",
    participantsInternal: "Participants - Internal",
    pocsPresentedCount: "PoC's Presented",
    productsPresentedCount: "Products/Prototypes Presented",
    prototypesUploadedYukti: "Prototypes Uploaded in YUKTI",
    prototypesVerifiedRecommendedYukti: "Prototypes Verified & Recommended",
    remarks: "Remarks",
    startDate: "Dates",
    teamsRegisteredExternal: "Teams Registered - External",
    teamsRegisteredInternal: "Teams Registered - Internal",
    themeDomain: "Theme/Domain",
    venue: "Venue",
  },
  "innovations": {
    academicYear: "A.Y.",
    briefDescription: "Brief Description",
    businessModelDetails: "Business Model Details",
    businessModelDeveloped: "Business Model Developed",
    competitionName: "Name of the Competition",
    contribution: "Contribution",
    department: "Dept. of Faculty",
    facultyInvolvedCount: "No. of Faculty Involved",
    facultyMentorName: "Name of the Faculty Mentor",
    incubationName: "Name of the Incubation",
    innovationTitle: "Title",
    innovationType: "Innovation Type",
    innovatorType: "Innovator",
    name: "Name of the Faculty",
    organizedBy: "Organized By",
    presentedInCompetition: "Presented in Competition",
    problemStatement: "Problem Statement",
    prototypeDetails: "Prototype Details",
    prototypeDeveloped: "Prototype Developed",
    remarks: "Remarks",
    startupFormed: "Start-up Formed",
    startupName: "Start-up Name",
    studentDepartment: "Department",
    studentName: "Name of the Student",
    studentRegdNo: "Regd. No.",
    studentYearOfStudy: "Year of Study",
    trlLevel: "TRL Level",
    verifiedRecommendedYukti: "Verified & Recommended in YUKTI",
    yuktiId: "YUKTI ID",
  },};
