// Faculty CSV column definitions.
//
// IMPORT_COLUMNS/IMPORT_HINTS (below COLUMNS/HINTS) are the only columns the
// bulk-import template (src/app/(dashboard)/hod/faculty/import/page.tsx) and
// import route (src/app/api/college/faculty/import/route.ts) accept -
// deliberately just the core identity/employment fields, not the full
// Academic Profile. COLUMNS/HINTS remain the full column set used only by the
// full-detail export (src/lib/faculty/exportFacultyCsv.ts) - import and
// export are intentionally no longer symmetric.

export interface FacultyCsvColumn {
  key: string;
  label: string;
  required: boolean;
  sample: string;
  // Alternate header wordings that should still map to this column (see matchHeaders in csv.ts).
  aliases?: string[];
}

export const COLUMNS: FacultyCsvColumn[] = [
  { key: "employeeId",        label: "Employee ID",                  required: true,  sample: "VIT001", aliases: ["Emp ID", "Employee Code", "Employee No", "Staff ID"] },
  { key: "name",               label: "Name",                         required: true,  sample: "Dr. A. Ravi Kumar", aliases: ["Faculty Name", "Full Name", "Employee Name"] },
  { key: "apaarFacultyId",     label: "APAAR Faculty ID",             required: false, sample: "", aliases: ["APAAR ID"] },
  { key: "email",              label: "Personal Email",               required: true,  sample: "ravi@gmail.com", aliases: ["Email", "Email ID", "Personal Email ID"] },
  { key: "password",          label: "Login Password (min 8 characters, optional)", required: false, sample: "", aliases: ["Password", "Login Password"] },
  { key: "phone",              label: "Phone",                        required: false, sample: "9876543210", aliases: ["Mobile", "Mobile Number", "Phone Number", "Contact Number"] },
  { key: "designation",        label: "Designation",                  required: true,  sample: "Asst. Prof." },
  { key: "qualification",      label: "Qualification",                required: true,  sample: "M.Tech" },
  { key: "specialization",     label: "Specialization",               required: false, sample: "Machine Learning" },
  { key: "employmentType",     label: "Employment Type",              required: true,  sample: "Regular", aliases: ["Employment", "Type of Employment"] },
  { key: "status",             label: "Status (Active/On Leave/Resigned/Retired)", required: false, sample: "Active", aliases: ["Status"] },
  { key: "joiningDate",        label: "Joining Date (YYYY-MM-DD)",    required: true,  sample: "2020-06-01", aliases: ["Joining Date", "Date of Joining", "DOJ"] },
  { key: "dateOfJoiningDepartment", label: "Date of Joining Department (YYYY-MM-DD)", required: false, sample: "", aliases: ["Department Joining Date"] },
  { key: "aicteEligible",      label: "AICTE Eligible (Yes/No)",      required: false, sample: "Yes" },
  { key: "experienceYears",    label: "Total Experience (Years)",      required: false, sample: "5" },
  { key: "internalExperience", label: "Internal Exp (Years)",         required: false, sample: "3" },
  { key: "externalExperience", label: "External Exp (Years)",         required: false, sample: "1" },
  { key: "inCampusExperience", label: "In Campus Exp (Years)",        required: false, sample: "1" },
  { key: "industryExperience", label: "Industry Exp (Years)",         required: false, sample: "2" },
  { key: "researchExperience", label: "Research Exp (Years)",         required: false, sample: "0" },
  { key: "gender",            label: "Gender",                       required: false, sample: "Male" },
  { key: "dateOfBirth",       label: "Date of Birth (YYYY-MM-DD)",   required: false, sample: "1990-05-15" },
  { key: "legalName",         label: "Legal Name (as per SSC)",      required: false, sample: "RAVI KUMAR ANNAPU" },
  { key: "fatherName",        label: "Father / Husband Name",        required: false, sample: "ANNAPU SRINIVAS" },
  { key: "motherName",        label: "Mother Name",                  required: false, sample: "ANNAPU LAKSHMI" },
  { key: "aadharNo",          label: "Aadhar No",                    required: false, sample: "1234 5678 9012" },
  { key: "panNo",             label: "PAN No",                       required: false, sample: "ABCDE1234F" },
  { key: "passportNumber",    label: "Passport No",                  required: false, sample: "" },
  { key: "emergencyContactName",  label: "Emergency Contact Name",   required: false, sample: "" },
  { key: "emergencyContactPhone", label: "Emergency Contact Phone",  required: false, sample: "" },
  { key: "religion",          label: "Religion",                     required: false, sample: "Hindu" },
  { key: "caste",             label: "Caste",                        required: false, sample: "OC" },
  { key: "subCaste",          label: "Sub Caste",                    required: false, sample: "" },
  { key: "collegeEmail",      label: "College Email",                required: false, sample: "ravi@vishnu.edu.in" },
  { key: "ratificationStatus",label: "Ratification Status",          required: false, sample: "Ratified" },
  { key: "ratificationDate",  label: "Ratification Date (YYYY-MM-DD)", required: false, sample: "2021-04-27" },
  { key: "hasPHD",            label: "Has PhD (Yes/No)",             required: false, sample: "No" },

  // ─── Family & Other Details ───────────────────────────────────────────────────
  { key: "maritalStatus",     label: "Marital Status (Single/Married)", required: false, sample: "Married" },
  { key: "spouseName",        label: "Spouse Name",                  required: false, sample: "" },
  { key: "numberOfChildren",  label: "Number of Children",           required: false, sample: "" },
  { key: "referral",          label: "Referral (if any)",            required: false, sample: "" },
  { key: "nativePlace",       label: "Native Place",                 required: false, sample: "Vijayawada" },
  { key: "bloodGroup",        label: "Blood Group",                  required: false, sample: "O+" },
  { key: "temporaryAddress",  label: "Temporary Address",            required: false, sample: "" },
  { key: "permanentSameAsTemporary", label: "Permanent Same as Temporary (Yes/No)", required: false, sample: "Yes" },
  { key: "permanentAddress",  label: "Permanent Address",            required: false, sample: "" },

  // ─── Academic Profile (Modules 1-5) - all optional ───────────────────────────
  { key: "highestQualification",   label: "Highest Qualification Earned",       required: false, sample: "Ph.D" },
  { key: "ug_degree",              label: "UG Degree",                          required: false, sample: "B.Tech" },
  { key: "ug_branch",              label: "UG Branch",                          required: false, sample: "CSE" },
  { key: "ug_university",          label: "UG University/Institute",            required: false, sample: "JNTU Kakinada" },
  { key: "ug_percentage",          label: "UG Percentage/CGPA",                 required: false, sample: "78%" },
  { key: "ug_year",                label: "UG Year of Completion",              required: false, sample: "2008" },
  { key: "pg_degree",              label: "PG Degree",                          required: false, sample: "M.Tech" },
  { key: "pg_branch",              label: "PG Branch",                          required: false, sample: "CSE" },
  { key: "pg_university",          label: "PG University/Institute",            required: false, sample: "NIT Warangal" },
  { key: "pg_percentage",          label: "PG Percentage/CGPA",                 required: false, sample: "82%" },
  { key: "pg_year",                label: "PG Year of Completion",              required: false, sample: "2011" },
  { key: "phd_degree",             label: "PhD Degree",                         required: false, sample: "Ph.D" },
  { key: "phd_specialization",     label: "PhD Specialization",                 required: false, sample: "Machine Learning" },
  { key: "phd_university",         label: "PhD University/Institute",           required: false, sample: "IIT Hyderabad" },
  { key: "phd_year",               label: "PhD Year of Completion",             required: false, sample: "2017" },
  { key: "postdoc_degree",         label: "Post-Doctoral Degree",               required: false, sample: "" },
  { key: "postdoc_branch",         label: "Post-Doctoral Branch",               required: false, sample: "" },
  { key: "postdoc_university",     label: "Post-Doctoral University/Institute", required: false, sample: "" },
  { key: "postdoc_percentage",     label: "Post-Doctoral Percentage/CGPA",      required: false, sample: "" },
  { key: "postdoc_year",           label: "Post-Doctoral Year of Completion",   required: false, sample: "" },
  { key: "phdStatus",              label: "Ph.D. Status (Awarded/Pursuing)",    required: false, sample: "Awarded" },
  { key: "phdMode",                label: "Ph.D. Mode (Full-Time/Part-Time)",   required: false, sample: "Full-Time" },
  { key: "phdSupervisorName",      label: "Ph.D. Project Supervisor Name",      required: false, sample: "Dr. S. Rao" },
  { key: "fellowshipsReceived",    label: "Fellowships Received",               required: false, sample: "UGC-NET JRF" },
  { key: "gateQualifiedYear",      label: "GATE Qualified Year",                required: false, sample: "2009" },
  { key: "gateScore",              label: "GATE Score",                         required: false, sample: "650" },
  { key: "netSletQualificationYear", label: "NET/SLET Qualification Year",      required: false, sample: "2010" },
  { key: "promotion1_fromDesignation", label: "Promotion 1 - From Designation", required: false, sample: "" },
  { key: "promotion1_toDesignation",   label: "Promotion 1 - To Designation",   required: false, sample: "" },
  { key: "promotion1_effectiveYear",   label: "Promotion 1 - Effective Year",   required: false, sample: "" },
  { key: "promotion2_fromDesignation", label: "Promotion 2 - From Designation", required: false, sample: "" },
  { key: "promotion2_toDesignation",   label: "Promotion 2 - To Designation",   required: false, sample: "" },
  { key: "promotion2_effectiveYear",   label: "Promotion 2 - Effective Year",   required: false, sample: "" },
  { key: "promotion3_fromDesignation", label: "Promotion 3 - From Designation", required: false, sample: "" },
  { key: "promotion3_toDesignation",   label: "Promotion 3 - To Designation",   required: false, sample: "" },
  { key: "promotion3_effectiveYear",   label: "Promotion 3 - Effective Year",   required: false, sample: "" },
  { key: "previousInstitution1_name",  label: "Previous Institution 1 - Name",        required: false, sample: "" },
  { key: "previousInstitution1_designation", label: "Previous Institution 1 - Designation", required: false, sample: "" },
  { key: "previousInstitution1_years", label: "Previous Institution 1 - Years Worked", required: false, sample: "" },
  { key: "previousInstitution2_name",  label: "Previous Institution 2 - Name",        required: false, sample: "" },
  { key: "previousInstitution2_designation", label: "Previous Institution 2 - Designation", required: false, sample: "" },
  { key: "previousInstitution2_years", label: "Previous Institution 2 - Years Worked", required: false, sample: "" },
  { key: "previousInstitution3_name",  label: "Previous Institution 3 - Name",        required: false, sample: "" },
  { key: "previousInstitution3_designation", label: "Previous Institution 3 - Designation", required: false, sample: "" },
  { key: "previousInstitution3_years", label: "Previous Institution 3 - Years Worked", required: false, sample: "" },
  { key: "primaryTeachingRole",    label: "Primary Teaching Role/Specialization", required: false, sample: "Data Structures" },
  { key: "course1_code",           label: "Course 1 - Code",                    required: false, sample: "CS201" },
  { key: "course1_name",           label: "Course 1 - Name",                    required: false, sample: "Data Structures" },
  { key: "course1_hours",          label: "Course 1 - Weekly Credit Hours",     required: false, sample: "4" },
  { key: "course2_code",           label: "Course 2 - Code",                    required: false, sample: "CS305" },
  { key: "course2_name",           label: "Course 2 - Name",                    required: false, sample: "Algorithms" },
  { key: "course2_hours",          label: "Course 2 - Weekly Credit Hours",     required: false, sample: "4" },
  { key: "course3_code",           label: "Course 3 - Code",                    required: false, sample: "" },
  { key: "course3_name",           label: "Course 3 - Name",                    required: false, sample: "" },
  { key: "course3_hours",          label: "Course 3 - Weekly Credit Hours",     required: false, sample: "" },
  { key: "publication1_title",     label: "Publication 1 - Title",              required: false, sample: "" },
  { key: "publication1_coAuthors", label: "Publication 1 - Co-Authors",         required: false, sample: "" },
  { key: "publication1_journal",   label: "Publication 1 - Journal/Conference", required: false, sample: "" },
  { key: "publication1_year",      label: "Publication 1 - Year",               required: false, sample: "" },
  { key: "publication1_indexing",  label: "Publication 1 - Indexing",           required: false, sample: "" },
  { key: "publication2_title",     label: "Publication 2 - Title",              required: false, sample: "" },
  { key: "publication2_coAuthors", label: "Publication 2 - Co-Authors",         required: false, sample: "" },
  { key: "publication2_journal",   label: "Publication 2 - Journal/Conference", required: false, sample: "" },
  { key: "publication2_year",      label: "Publication 2 - Year",               required: false, sample: "" },
  { key: "publication2_indexing",  label: "Publication 2 - Indexing",           required: false, sample: "" },
  { key: "publication3_title",     label: "Publication 3 - Title",              required: false, sample: "" },
  { key: "publication3_coAuthors", label: "Publication 3 - Co-Authors",         required: false, sample: "" },
  { key: "publication3_journal",   label: "Publication 3 - Journal/Conference", required: false, sample: "" },
  { key: "publication3_year",      label: "Publication 3 - Year",               required: false, sample: "" },
  { key: "publication3_indexing",  label: "Publication 3 - Indexing",           required: false, sample: "" },
  { key: "publicationsFirstOrCorrespondingAuthor", label: "First/Corresponding Author Pubs", required: false, sample: "5" },
  { key: "publicationsQ1OrHighImpact",             label: "Q1 / IF>4.0 Pubs",               required: false, sample: "2" },
  { key: "sciScopusCount",         label: "SCI/Scopus Count",                   required: false, sample: "8" },
  { key: "wosCount",               label: "WoS (SCIE/ESCI) Count",              required: false, sample: "3" },
  { key: "conferencePapersCount",  label: "Conference Papers",                  required: false, sample: "4" },
  { key: "bookChaptersCount",      label: "Book Chapters",                      required: false, sample: "1" },
  { key: "reviewPublicationsCount",label: "Review Publications",                required: false, sample: "0" },
  { key: "totalPublications",      label: "Total Publications (incl. co-authorship)", required: false, sample: "12" },
  { key: "totalCitations",         label: "Total Citations",                    required: false, sample: "45" },
  { key: "hIndex",                 label: "H-Index",                            required: false, sample: "4" },
  { key: "i10Index",               label: "i10-Index",                          required: false, sample: "2" },
  { key: "googleScholarId",        label: "Google Scholar ID",                  required: false, sample: "" },
  { key: "scopusAuthorId",         label: "Scopus Author ID",                   required: false, sample: "" },
  { key: "orcidId",                label: "ORCID iD",                           required: false, sample: "" },
  { key: "project1_title",         label: "Funded Project 1 - Title",           required: false, sample: "" },
  { key: "project1_agency",        label: "Funded Project 1 - Funding Agency",  required: false, sample: "" },
  { key: "project1_amount",        label: "Funded Project 1 - Grant Amount (₹L)", required: false, sample: "" },
  { key: "project1_year",          label: "Funded Project 1 - Year",            required: false, sample: "" },
  { key: "project1_status",        label: "Funded Project 1 - Status",          required: false, sample: "" },
  { key: "project1_role",          label: "Funded Project 1 - Role (PI/Co-PI)", required: false, sample: "" },
  { key: "project2_title",         label: "Funded Project 2 - Title",           required: false, sample: "" },
  { key: "project2_agency",        label: "Funded Project 2 - Funding Agency",  required: false, sample: "" },
  { key: "project2_amount",        label: "Funded Project 2 - Grant Amount (₹L)", required: false, sample: "" },
  { key: "project2_year",          label: "Funded Project 2 - Year",            required: false, sample: "" },
  { key: "project2_status",        label: "Funded Project 2 - Status",          required: false, sample: "" },
  { key: "project2_role",          label: "Funded Project 2 - Role (PI/Co-PI)", required: false, sample: "" },
  { key: "project3_title",         label: "Funded Project 3 - Title",           required: false, sample: "" },
  { key: "project3_agency",        label: "Funded Project 3 - Funding Agency",  required: false, sample: "" },
  { key: "project3_amount",        label: "Funded Project 3 - Grant Amount (₹L)", required: false, sample: "" },
  { key: "project3_year",          label: "Funded Project 3 - Year",            required: false, sample: "" },
  { key: "project3_status",        label: "Funded Project 3 - Status",          required: false, sample: "" },
  { key: "project3_role",          label: "Funded Project 3 - Role (PI/Co-PI)", required: false, sample: "" },
  { key: "consultancy1_title",     label: "Consultancy 1 - Title",              required: false, sample: "" },
  { key: "consultancy1_client",    label: "Consultancy 1 - Client/Agency",      required: false, sample: "" },
  { key: "consultancy1_revenue",   label: "Consultancy 1 - Revenue (₹L)",       required: false, sample: "" },
  { key: "consultancy1_year",      label: "Consultancy 1 - Year",               required: false, sample: "" },
  { key: "consultancy1_status",    label: "Consultancy 1 - Status",             required: false, sample: "" },
  { key: "consultancy2_title",     label: "Consultancy 2 - Title",              required: false, sample: "" },
  { key: "consultancy2_client",    label: "Consultancy 2 - Client/Agency",      required: false, sample: "" },
  { key: "consultancy2_revenue",   label: "Consultancy 2 - Revenue (₹L)",       required: false, sample: "" },
  { key: "consultancy2_year",      label: "Consultancy 2 - Year",               required: false, sample: "" },
  { key: "consultancy2_status",    label: "Consultancy 2 - Status",             required: false, sample: "" },
  { key: "consultancy3_title",     label: "Consultancy 3 - Title",              required: false, sample: "" },
  { key: "consultancy3_client",    label: "Consultancy 3 - Client/Agency",      required: false, sample: "" },
  { key: "consultancy3_revenue",   label: "Consultancy 3 - Revenue (₹L)",       required: false, sample: "" },
  { key: "consultancy3_year",      label: "Consultancy 3 - Year",               required: false, sample: "" },
  { key: "consultancy3_status",    label: "Consultancy 3 - Status",             required: false, sample: "" },
  { key: "patentIndianFiled",      label: "Patents - Indian Filed",             required: false, sample: "1" },
  { key: "patentIndianPublished",  label: "Patents - Indian Published",         required: false, sample: "1" },
  { key: "patentIndianGranted",    label: "Patents - Indian Granted",           required: false, sample: "0" },
  { key: "patentInternationalFiled",     label: "Patents - International Filed",     required: false, sample: "0" },
  { key: "patentInternationalPublished", label: "Patents - International Published", required: false, sample: "0" },
  { key: "patentInternationalGranted",   label: "Patents - International Granted",   required: false, sample: "0" },
  { key: "patentDetails",          label: "Patents - Details",                  required: false, sample: "" },
  { key: "phdScholarsPursuingCount",       label: "Ph.D. Scholars Pursuing - Count",        required: false, sample: "1" },
  { key: "phdScholarsPursuingUniversities", label: "Ph.D. Scholars Pursuing - Universities", required: false, sample: "JNTUK" },
  { key: "phdScholarsAwardedCount",        label: "Ph.D. Scholars Awarded - Count",         required: false, sample: "0" },
  { key: "phdScholarsAwardedUniversities", label: "Ph.D. Scholars Awarded - Universities",  required: false, sample: "" },
  { key: "nationalExposure",       label: "National Exposure (joint pubs w/ IITs/NITs/IIITs/CSIR)", required: false, sample: "" },
  { key: "internationalExposure",  label: "International Exposure (joint pubs w/ foreign universities)", required: false, sample: "" },
  { key: "lab1_details",           label: "New Lab 1 - Facility Details",       required: false, sample: "" },
  { key: "lab1_outcomes",          label: "New Lab 1 - Outcomes",               required: false, sample: "" },
  { key: "lab2_details",           label: "New Lab 2 - Facility Details",       required: false, sample: "" },
  { key: "lab2_outcomes",          label: "New Lab 2 - Outcomes",               required: false, sample: "" },
  { key: "lab3_details",           label: "New Lab 3 - Facility Details",       required: false, sample: "" },
  { key: "lab3_outcomes",          label: "New Lab 3 - Outcomes",               required: false, sample: "" },

  // Structured entries matching the Add/Edit Faculty form's repeating groups -
  // the free-text fields below (administrativeResponsibilities, certificationsAndFdps,
  // professionalBodyMemberships, notableAwards) are legacy: the form only
  // displays them read-only now, it doesn't let you edit them, use these instead.
  { key: "adminResp1_category",    label: "Admin Responsibility 1 - Category",  required: false, sample: "" },
  { key: "adminResp1_description", label: "Admin Responsibility 1 - Description", required: false, sample: "" },
  { key: "adminResp1_fromYear",    label: "Admin Responsibility 1 - From Year", required: false, sample: "" },
  { key: "adminResp1_toYear",      label: "Admin Responsibility 1 - To Year (blank = ongoing)", required: false, sample: "" },
  { key: "adminResp2_category",    label: "Admin Responsibility 2 - Category",  required: false, sample: "" },
  { key: "adminResp2_description", label: "Admin Responsibility 2 - Description", required: false, sample: "" },
  { key: "adminResp2_fromYear",    label: "Admin Responsibility 2 - From Year", required: false, sample: "" },
  { key: "adminResp2_toYear",      label: "Admin Responsibility 2 - To Year (blank = ongoing)", required: false, sample: "" },
  { key: "adminResp3_category",    label: "Admin Responsibility 3 - Category",  required: false, sample: "" },
  { key: "adminResp3_description", label: "Admin Responsibility 3 - Description", required: false, sample: "" },
  { key: "adminResp3_fromYear",    label: "Admin Responsibility 3 - From Year", required: false, sample: "" },
  { key: "adminResp3_toYear",      label: "Admin Responsibility 3 - To Year (blank = ongoing)", required: false, sample: "" },
  { key: "administrativeResponsibilities", label: "Administrative Responsibilities Held (+achievements) - legacy, read-only in the form", required: false, sample: "" },
  { key: "training1_type",         label: "Training 1 - Type",                  required: false, sample: "" },
  { key: "training1_role",         label: "Training 1 - Participated/Conducted", required: false, sample: "" },
  { key: "training1_title",        label: "Training 1 - Title",                 required: false, sample: "" },
  { key: "training1_organizer",    label: "Training 1 - Organizer",             required: false, sample: "" },
  { key: "training1_year",         label: "Training 1 - Year",                  required: false, sample: "" },
  { key: "training1_durationDays", label: "Training 1 - Duration (Days)",       required: false, sample: "" },
  { key: "training2_type",         label: "Training 2 - Type",                  required: false, sample: "" },
  { key: "training2_role",         label: "Training 2 - Participated/Conducted", required: false, sample: "" },
  { key: "training2_title",        label: "Training 2 - Title",                 required: false, sample: "" },
  { key: "training2_organizer",    label: "Training 2 - Organizer",             required: false, sample: "" },
  { key: "training2_year",         label: "Training 2 - Year",                  required: false, sample: "" },
  { key: "training2_durationDays", label: "Training 2 - Duration (Days)",       required: false, sample: "" },
  { key: "training3_type",         label: "Training 3 - Type",                  required: false, sample: "" },
  { key: "training3_role",         label: "Training 3 - Participated/Conducted", required: false, sample: "" },
  { key: "training3_title",        label: "Training 3 - Title",                 required: false, sample: "" },
  { key: "training3_organizer",    label: "Training 3 - Organizer",             required: false, sample: "" },
  { key: "training3_year",         label: "Training 3 - Year",                  required: false, sample: "" },
  { key: "training3_durationDays", label: "Training 3 - Duration (Days)",       required: false, sample: "" },
  { key: "certificationsAndFdps",  label: "Certifications/FDPs (NPTEL/Coursera/AICTE) - legacy, read-only in the form", required: false, sample: "" },
  { key: "membership1_body",         label: "Membership 1 - Body",              required: false, sample: "" },
  { key: "membership1_otherName",    label: "Membership 1 - Body Name (if Other)", required: false, sample: "" },
  { key: "membership1_membershipId", label: "Membership 1 - Membership ID",     required: false, sample: "" },
  { key: "membership1_sinceYear",    label: "Membership 1 - Member Since (Year)", required: false, sample: "" },
  { key: "membership2_body",         label: "Membership 2 - Body",              required: false, sample: "" },
  { key: "membership2_otherName",    label: "Membership 2 - Body Name (if Other)", required: false, sample: "" },
  { key: "membership2_membershipId", label: "Membership 2 - Membership ID",     required: false, sample: "" },
  { key: "membership2_sinceYear",    label: "Membership 2 - Member Since (Year)", required: false, sample: "" },
  { key: "membership3_body",         label: "Membership 3 - Body",              required: false, sample: "" },
  { key: "membership3_otherName",    label: "Membership 3 - Body Name (if Other)", required: false, sample: "" },
  { key: "membership3_membershipId", label: "Membership 3 - Membership ID",     required: false, sample: "" },
  { key: "membership3_sinceYear",    label: "Membership 3 - Member Since (Year)", required: false, sample: "" },
  { key: "professionalBodyMemberships", label: "Professional Body Memberships (IEEE/ACM/CSI) - legacy, read-only in the form", required: false, sample: "" },
  { key: "book1_title",            label: "Authored Book 1 - Title",            required: false, sample: "" },
  { key: "book1_publisher",        label: "Authored Book 1 - Publisher",        required: false, sample: "" },
  { key: "book1_year",             label: "Authored Book 1 - Year",             required: false, sample: "" },
  { key: "book2_title",            label: "Authored Book 2 - Title",            required: false, sample: "" },
  { key: "book2_publisher",        label: "Authored Book 2 - Publisher",        required: false, sample: "" },
  { key: "book2_year",             label: "Authored Book 2 - Year",             required: false, sample: "" },
  { key: "book3_title",            label: "Authored Book 3 - Title",            required: false, sample: "" },
  { key: "book3_publisher",        label: "Authored Book 3 - Publisher",        required: false, sample: "" },
  { key: "book3_year",             label: "Authored Book 3 - Year",             required: false, sample: "" },
  { key: "award1_category",     label: "Award 1 - Category",                    required: false, sample: "" },
  { key: "award1_title",        label: "Award 1 - Title",                       required: false, sample: "" },
  { key: "award1_awardingBody", label: "Award 1 - Awarding Body",               required: false, sample: "" },
  { key: "award1_year",         label: "Award 1 - Year",                        required: false, sample: "" },
  { key: "award2_category",     label: "Award 2 - Category",                    required: false, sample: "" },
  { key: "award2_title",        label: "Award 2 - Title",                       required: false, sample: "" },
  { key: "award2_awardingBody", label: "Award 2 - Awarding Body",               required: false, sample: "" },
  { key: "award2_year",         label: "Award 2 - Year",                        required: false, sample: "" },
  { key: "award3_category",     label: "Award 3 - Category",                    required: false, sample: "" },
  { key: "award3_title",        label: "Award 3 - Title",                       required: false, sample: "" },
  { key: "award3_awardingBody", label: "Award 3 - Awarding Body",               required: false, sample: "" },
  { key: "award3_year",         label: "Award 3 - Year",                        required: false, sample: "" },
  { key: "notableAwards",          label: "Notable Awards - legacy, read-only in the form", required: false, sample: "" },

  // ─── Financial Standing & Budgetary Impact (Module 6) ────────────────────────
  { key: "presentSalary",          label: "Present Salary (₹)",                 required: false, sample: "" },
  { key: "grossAnnualCTC",         label: "Gross Annual CTC (₹)",               required: false, sample: "" },
  { key: "incrementsAwarded",      label: "Increments Awarded",                 required: false, sample: "" },
  { key: "fundingConsultancyRevenue", label: "Funding/Consultancy Revenue Generation (₹)", required: false, sample: "" },

  // ─── Others (Module 7) ────────────────────────────────────────────────────────
  { key: "otherInformation",       label: "Other Information",                  required: false, sample: "" },

  // Resume/CV - Teaching Faculty only, no equivalent on the Supporting Staff
  // templates (src/lib/supportingStaff/csvColumns.ts). A link to an
  // already-hosted file (Drive/Storage) - this template can't upload files
  // directly.
  { key: "resumeUrl",              label: "Resume/CV URL",                      required: false, sample: "" },
];

export const HINTS = [
  "Designation: any teaching title used by your college (e.g. Professor, Assoc. Prof., Asst. Prof., Lecturer, Visiting Faculty, Adjunct Faculty for Engineering/Pharmacy/Dental; Principal, HOD, PGT, TGT, PRT etc. for Degree/Polytechnic/School colleges)",
  "Employment Type: Regular, Permanent, Contract, Visiting, Part-Time",
  "Status: Active, On Leave, Resigned, Retired (defaults to Active if left blank)",
  "Gender: Male, Female, Other",
  "Marital Status: Single, Married",
  "Ratification Status: Ratified, Not Ratified",
  "Has PhD: Yes or No",
  "AICTE Eligible: Yes or No",
  "Funded Project Role: PI or Co-PI",
  "Admin Responsibility Category: Coordinator Role, Committee Membership, NBA / NAAC Work, IQAC, Examination Duty, Other",
  "Training Type: FDP, Workshop, MOOC, Certification, Skill Development, Administrative Training, ERP Training, Office Automation Training, Other",
  "Membership Body: IEEE, ISTE, CSI, ACM, IEI, Other",
  "Award Category: Best Teacher Award, Research Award, Appreciation Certificate, Other",
  "Dates must be in YYYY-MM-DD format (e.g. 2020-06-01)",
  "Department is auto-assigned from your HOD profile",
  "Login Password (optional): fill this in to create the faculty member's login account (as a Panel Member) automatically during import, using their College Email (or Personal Email if no College Email is given) as the login ID - must be at least 8 characters. Leave it blank to skip login creation for that row; you can still set it up later from the Faculty list's \"Set Login\" button.",
  "Resume/CV URL: an already-hosted link (Drive/Storage) - this template doesn't upload files directly; use the faculty edit page's Documents section to upload one",
];

// A column present in the export but never accepted back on import
// (Current Teaching is relational - sourced from the Teaching Assignments module).
export const TEACHING_SUMMARY_COLUMN: FacultyCsvColumn = {
  key: "currentTeachingSummary",
  label: "Current Teaching (Course / Year / Section / Subject)",
  required: false,
  sample: "",
};

// ─── Bulk-import template - core fields only ──────────────────────────────────
// The rest of a faculty member's record (personal details, Academic Profile,
// Technical Profile, etc.) is filled in afterward from the Edit Faculty page -
// bulk import is for quickly getting people into the system, not a full data
// migration path.
export const IMPORT_COLUMNS: FacultyCsvColumn[] = [
  { key: "employeeId",   label: "Employee ID",   required: true,  sample: "VIT001", aliases: ["Emp ID", "Employee Code", "Employee No", "Staff ID"] },
  { key: "name",         label: "Full Name",     required: true,  sample: "Dr. A. Ravi Kumar", aliases: ["Faculty Name", "Name", "Employee Name"] },
  { key: "apaarFacultyId", label: "APAAR Faculty ID", required: false, sample: "", aliases: ["APAAR ID"] },
  { key: "collegeEmail", label: "College Email", required: true,  sample: "ravi@vishnu.edu.in", aliases: ["Email", "Email ID"] },
  { key: "phone",        label: "Phone",         required: false, sample: "9876543210", aliases: ["Mobile", "Mobile Number", "Phone Number", "Contact Number"] },
  { key: "password",     label: "Login Password (min 8 characters, optional)", required: false, sample: "", aliases: ["Password"] },
  { key: "designation",  label: "Designation",   required: true,  sample: "Asst. Prof." },
  { key: "qualification", label: "Highest Qualification", required: true, sample: "M.Tech", aliases: ["Qualification"] },
  { key: "specialization", label: "Specialization", required: false, sample: "Machine Learning" },
  { key: "experienceYears", label: "Years of Experience", required: false, sample: "5", aliases: ["Experience", "Total Experience"] },
  { key: "employmentType", label: "Employment Type", required: true, sample: "Regular", aliases: ["Employment", "Type of Employment"] },
  { key: "joiningDate",  label: "Date of Joining Institution (YYYY-MM-DD)", required: true, sample: "2020-06-01", aliases: ["Joining Date", "Date of Joining", "DOJ"] },
  { key: "dateOfJoiningDepartment", label: "Date of Joining Department (YYYY-MM-DD)", required: false, sample: "", aliases: ["Department Joining Date"] },

  // ─── Personal / statutory details (all optional) ──────────────────────────────
  { key: "gender",            label: "Gender",                       required: false, sample: "Male" },
  { key: "dateOfBirth",       label: "Date of Birth (YYYY-MM-DD)",   required: false, sample: "1990-05-15", aliases: ["DOB"] },
  { key: "legalName",         label: "Legal Name (as per SSC)",      required: false, sample: "" },
  { key: "fatherName",        label: "Father / Husband Name",        required: false, sample: "" },
  { key: "motherName",        label: "Mother Name",                  required: false, sample: "" },
  { key: "aadharNo",          label: "Aadhar No",                    required: false, sample: "" },
  { key: "panNo",             label: "PAN No",                       required: false, sample: "" },
  { key: "passportNumber",    label: "Passport No",                  required: false, sample: "" },
  { key: "emergencyContactName",  label: "Emergency Contact Name",   required: false, sample: "" },
  { key: "emergencyContactPhone", label: "Emergency Contact Phone",  required: false, sample: "" },
  { key: "religion",          label: "Religion",                     required: false, sample: "Hindu" },
  { key: "caste",             label: "Caste",                        required: false, sample: "OC" },
  { key: "subCaste",          label: "Sub Caste",                    required: false, sample: "" },
  { key: "ratificationStatus",label: "Ratification Status",          required: false, sample: "" },
  { key: "ratificationDate",  label: "Ratification Date (YYYY-MM-DD)", required: false, sample: "" },
  { key: "maritalStatus",     label: "Marital Status (Single/Married)", required: false, sample: "" },
  { key: "spouseName",        label: "Spouse Name",                  required: false, sample: "" },
  { key: "numberOfChildren",  label: "Number of Children",           required: false, sample: "" },
  { key: "referral",          label: "Referral (if any)",            required: false, sample: "" },
  { key: "nativePlace",       label: "Native Place",                 required: false, sample: "" },
  { key: "bloodGroup",        label: "Blood Group",                  required: false, sample: "" },
  { key: "temporaryAddress",  label: "Temporary Address",            required: false, sample: "" },
  { key: "permanentSameAsTemporary", label: "Permanent Same as Temporary (Yes/No)", required: false, sample: "" },
  { key: "permanentAddress",  label: "Permanent Address",            required: false, sample: "" },
];

export const IMPORT_HINTS = [
  "Designation: any teaching title used by your college (e.g. Professor, Assoc. Prof., Asst. Prof., Lecturer, Visiting Faculty, Adjunct Faculty for Engineering/Pharmacy/Dental; Principal, HOD, PGT, TGT, PRT etc. for Degree/Polytechnic/School colleges) - Supporting Staff (Lab Assistant, Programmer, Office Assistant, etc.) is added from the Supporting Staff module instead",
  "Employment Type: Regular, Permanent, Contract, Visiting, Part-Time",
  "Dates must be in YYYY-MM-DD format (e.g. 2020-06-01)",
  "Department is auto-assigned from your HOD profile",
  "Login Password (optional): fill this in to create the faculty member's login account (as a Panel Member) automatically during import, using their College Email as the login ID - must be at least 8 characters. Leave it blank to skip login creation for that row; you can still set it up later from the Faculty list's \"Set Login\" button.",
  "Personal details and Academic Profile aren't part of this template - fill those in afterward from the Edit Faculty page.",
];
