// Full-detail staff (FMSUser) CSV export column definitions - mirrors the shape of
// src/lib/faculty/csvColumns.ts but for Principal-managed staff (HOD / Vice Principal /
// College Office), whose personal-detail and academic-profile fields share the same
// names/types as FacultyMember.

export interface StaffCsvColumn {
  key: string;
  label: string;
}

export const STAFF_COLUMNS: StaffCsvColumn[] = [
  { key: "role",               label: "Role" },
  { key: "name",                label: "Name" },
  { key: "email",                label: "Email" },
  { key: "collegeEmail",          label: "College Email" },
  { key: "phone",                 label: "Phone" },
  { key: "employeeId",             label: "Employee ID" },
  { key: "designation",             label: "Designation" },
  { key: "department",               label: "Department" },
  { key: "dateOfBirth",               label: "Date of Birth" },
  { key: "isActive",                   label: "Active" },
  { key: "gender",                      label: "Gender" },
  { key: "legalName",                    label: "Legal Name (as per SSC)" },
  { key: "fatherName",                    label: "Father Name" },
  { key: "motherName",                     label: "Mother Name" },
  { key: "religion",                        label: "Religion" },
  { key: "caste",                            label: "Caste" },
  { key: "subCaste",                        label: "Sub Caste" },
  { key: "aadharNo",                          label: "Aadhar No" },
  { key: "panNo",                              label: "PAN No" },
  { key: "passportNo",                      label: "Passport No" },
  { key: "bankAccountNumber",                        label: "Bank Account Number" },
  { key: "ifscCode",                              label: "IFSC Code" },
  { key: "bankName",                               label: "Bank Name" },
  { key: "bankBranch",                              label: "Bank Branch" },
  { key: "bankOtherDetails",                         label: "Bank Other Details" },
  { key: "emergencyContactName",                 label: "Emergency Contact Name" },
  { key: "emergencyContactRelation",             label: "Emergency Contact Relation" },
  { key: "emergencyContactMobileNo",                 label: "Emergency Contact Mobile No" },
  { key: "ratificationStatus",                  label: "Ratification Status" },
  { key: "ratificationProceedingsNumber",        label: "Ratification Proceedings Number" },
  { key: "ratificationDate",                     label: "Ratification Date" },

  // ─── Family & Other Details ─────────────────────────────────────────────
  { key: "maritalStatus",             label: "Marital Status (Single/Married)" },
  { key: "spouseName",                 label: "Spouse Name" },
  { key: "numberOfChildren",            label: "Number of Children" },
  { key: "bloodGroup",                     label: "Blood Group" },
  { key: "temporaryAddress",                label: "Temporary Address" },
  { key: "permanentAddressSameAsTemporary",         label: "Permanent Address Same as Temporary (Yes/No)" },
  { key: "permanentAddress",                  label: "Permanent Address" },

  // ─── Academic Profile (Modules 1-5) - shown for HOD / Vice Principal ────
  { key: "highestQualification",   label: "Highest Qualification" },
  { key: "ug_degreeAndBranch",     label: "UG Course & Branch" },
  { key: "ug_university",          label: "UG Institution Name" },
  { key: "ug_percentage",          label: "UG Percentage / CGPA" },
  { key: "ug_year",                label: "UG Year of Passing" },
  { key: "pg_degreeAndBranch",     label: "PG Course & Branch" },
  { key: "pg_university",          label: "PG Institution Name" },
  { key: "pg_percentage",          label: "PG Percentage / CGPA" },
  { key: "pg_year",                label: "PG Year of Passing" },
  { key: "phd_specialization",     label: "PhD Specialization" },
  { key: "phd_university",         label: "PhD Institution Name" },
  { key: "phd_year",               label: "PhD Year of Award" },
  { key: "netSletSetGateOthers",   label: "NET/SLET/SET/GATE/Others" },
  { key: "qualifiedExam",          label: "Qualified Exam" },
  { key: "examScore",              label: "Exam Score" },
  { key: "qualifiedYear",          label: "Qualified Year" },
  { key: "academicExperience1_institutionName",  label: "Academic Experience 1 - Institution Name" },
  { key: "academicExperience1_designation", label: "Academic Experience 1 - Designation" },
  { key: "academicExperience1_fromDate", label: "Academic Experience 1 - From Date" },
  { key: "academicExperience1_toDate", label: "Academic Experience 1 - To Date" },
  { key: "academicExperience2_institutionName",  label: "Academic Experience 2 - Institution Name" },
  { key: "academicExperience2_designation", label: "Academic Experience 2 - Designation" },
  { key: "academicExperience2_fromDate", label: "Academic Experience 2 - From Date" },
  { key: "academicExperience2_toDate", label: "Academic Experience 2 - To Date" },
  { key: "academicExperience3_institutionName",  label: "Academic Experience 3 - Institution Name" },
  { key: "academicExperience3_designation", label: "Academic Experience 3 - Designation" },
  { key: "academicExperience3_fromDate", label: "Academic Experience 3 - From Date" },
  { key: "academicExperience3_toDate", label: "Academic Experience 3 - To Date" },
  { key: "teachingRolesResponsibilities", label: "Teaching Roles/Responsibilities" },
  { key: "industryRolesResponsibilities", label: "Industry Roles/Responsibilities" },
  { key: "researchRolesResponsibilities", label: "Research Roles/Responsibilities" },
  { key: "course1_code",           label: "Course 1 - Code" },
  { key: "course1_name",           label: "Course 1 - Name" },
  { key: "course1_hours",          label: "Course 1 - Weekly Credit Hours" },
  { key: "course2_code",           label: "Course 2 - Code" },
  { key: "course2_name",           label: "Course 2 - Name" },
  { key: "course2_hours",          label: "Course 2 - Weekly Credit Hours" },
  { key: "course3_code",           label: "Course 3 - Code" },
  { key: "course3_name",           label: "Course 3 - Name" },
  { key: "course3_hours",          label: "Course 3 - Weekly Credit Hours" },
  { key: "publication1_title",     label: "Publication 1 - Title" },
  { key: "publication1_coAuthors", label: "Publication 1 - Co-Authors" },
  { key: "publication1_journal",   label: "Publication 1 - Journal/Conference" },
  { key: "publication1_year",      label: "Publication 1 - Year" },
  { key: "publication1_indexing",  label: "Publication 1 - Indexing" },
  { key: "publication2_title",     label: "Publication 2 - Title" },
  { key: "publication2_coAuthors", label: "Publication 2 - Co-Authors" },
  { key: "publication2_journal",   label: "Publication 2 - Journal/Conference" },
  { key: "publication2_year",      label: "Publication 2 - Year" },
  { key: "publication2_indexing",  label: "Publication 2 - Indexing" },
  { key: "publication3_title",     label: "Publication 3 - Title" },
  { key: "publication3_coAuthors", label: "Publication 3 - Co-Authors" },
  { key: "publication3_journal",   label: "Publication 3 - Journal/Conference" },
  { key: "publication3_year",      label: "Publication 3 - Year" },
  { key: "publication3_indexing",  label: "Publication 3 - Indexing" },
  { key: "publicationsFirstOrCorrespondingAuthor", label: "First/Corresponding Author Pubs" },
  { key: "publicationsQ1OrHighImpact",             label: "Q1 / IF>4.0 Pubs" },
  { key: "sciScopusCount",         label: "SCI/Scopus Count" },
  { key: "wosCount",               label: "WoS (SCIE/ESCI) Count" },
  { key: "conferencePapersCount",  label: "Conference Papers" },
  { key: "bookChaptersCount",      label: "Book Chapters" },
  { key: "reviewPublicationsCount",label: "Review Publications" },
  { key: "totalPublications",      label: "Total Publications (incl. co-authorship)" },
  { key: "totalCitations",         label: "Total Citations" },
  { key: "hIndex",                 label: "H-Index" },
  { key: "i10Index",               label: "i10-Index" },
  { key: "lab1_details",           label: "New Lab 1 - Facility Details" },
  { key: "lab1_outcomes",          label: "New Lab 1 - Outcomes" },
  { key: "lab2_details",           label: "New Lab 2 - Facility Details" },
  { key: "lab2_outcomes",          label: "New Lab 2 - Outcomes" },
  { key: "lab3_details",           label: "New Lab 3 - Facility Details" },
  { key: "lab3_outcomes",          label: "New Lab 3 - Outcomes" },

  // ─── Financial Standing & Budgetary Impact (Module 6) ───────────────────
  { key: "monthlySalary",          label: "Monthly Salary (₹)" },
  { key: "grossAnnualCTC",         label: "Gross Annual CTC (₹)" },
  { key: "incrementsAwarded",      label: "Increments Awarded" },
  { key: "fundingConsultancyRevenueGeneration", label: "Funding/Consultancy Revenue Generation (₹)" },

  // ─── Others (Module 7) ───────────────────────────────────────────────────
  { key: "otherInformation",       label: "Other Information" },
];
