// Full-detail staff (FMSUser) CSV export column definitions — mirrors the shape of
// src/lib/faculty/csvColumns.ts but for Principal-managed staff (HOD / Vice Principal /
// College Office), whose personal-detail and academic-profile fields share the same
// names/types as FacultyMember.

export interface StaffCsvColumn {
  key: string;
  label: string;
}

export const STAFF_COLUMNS: StaffCsvColumn[] = [
  { key: "role",               label: "Role" },
  { key: "name",                label: "Name" },
  { key: "email",                label: "Email" },
  { key: "phone",                 label: "Phone" },
  { key: "employeeId",             label: "Employee ID" },
  { key: "designation",             label: "Designation" },
  { key: "department",               label: "Department" },
  { key: "dateOfBirth",               label: "Date of Birth" },
  { key: "isActive",                   label: "Active" },
  { key: "gender",                      label: "Gender" },
  { key: "legalName",                    label: "Legal Name (as per SSC)" },
  { key: "fatherName",                    label: "Father / Husband Name" },
  { key: "motherName",                     label: "Mother Name" },
  { key: "religion",                        label: "Religion" },
  { key: "caste",                            label: "Caste" },
  { key: "aadharNo",                          label: "Aadhar No" },
  { key: "panNo",                              label: "PAN No" },
  { key: "ratificationStatus",                  label: "Ratification Status" },
  { key: "ratificationDate",                     label: "Ratification Date" },

  // ─── Family & Other Details ─────────────────────────────────────────────
  { key: "maritalStatus",             label: "Marital Status (Single/Married)" },
  { key: "spouseName",                 label: "Spouse Name" },
  { key: "numberOfChildren",            label: "Number of Children" },
  { key: "referral",                     label: "Referral (if any)" },
  { key: "nativePlace",                   label: "Native Place" },
  { key: "bloodGroup",                     label: "Blood Group" },
  { key: "temporaryAddress",                label: "Temporary Address" },
  { key: "permanentSameAsTemporary",         label: "Permanent Same as Temporary (Yes/No)" },
  { key: "permanentAddress",                  label: "Permanent Address" },

  // ─── Academic Profile (Modules 1-5) — shown for HOD / Vice Principal ────
  { key: "highestQualification",   label: "Highest Qualification Earned" },
  { key: "ug_degreeAndBranch",     label: "UG Degree & Branch" },
  { key: "ug_university",          label: "UG University/Institute" },
  { key: "ug_percentage",          label: "UG Percentage/Division" },
  { key: "ug_year",                label: "UG Year of Completion" },
  { key: "pg_degreeAndBranch",     label: "PG Degree & Branch" },
  { key: "pg_university",          label: "PG University/Institute" },
  { key: "pg_percentage",          label: "PG Percentage/Division" },
  { key: "pg_year",                label: "PG Year of Completion" },
  { key: "phd_degreeAndBranch",    label: "PhD Degree & Branch" },
  { key: "phd_university",         label: "PhD University/Institute" },
  { key: "phd_percentage",         label: "PhD Percentage/Division" },
  { key: "phd_year",               label: "PhD Year of Completion" },
  { key: "phdStatus",              label: "Ph.D. Status (Awarded/Pursuing)" },
  { key: "phdMode",                label: "Ph.D. Mode (Full-Time/Part-Time)" },
  { key: "phdSupervisorName",      label: "Ph.D. Project Supervisor Name" },
  { key: "fellowshipsReceived",    label: "Fellowships Received" },
  { key: "gateQualifiedYear",      label: "GATE Qualified Year" },
  { key: "gateScore",              label: "GATE Score" },
  { key: "netSletQualificationYear", label: "NET/SLET Qualification Year" },
  { key: "teachingExperienceBeforeJoiningYears", label: "Teaching Exp Before Joining (yrs)" },
  { key: "teachingExperienceSinceJoiningYears",  label: "Teaching Exp Since Joining (yrs)" },
  { key: "researchOrIndustryExperienceYears",    label: "Research/Industry Exp (yrs)" },
  { key: "totalProfessionalExperienceYears",     label: "Total Professional Exp (yrs)" },
  { key: "totalWeeklyTeachingLoadHours",         label: "Total Weekly Teaching Load (Hrs)" },
  { key: "averageStudentFeedbackScore",          label: "Average Student Feedback Score" },
  { key: "primaryTeachingRole",    label: "Primary Teaching Role/Specialization" },
  { key: "course1_code",           label: "Course 1 - Code" },
  { key: "course1_name",           label: "Course 1 - Name" },
  { key: "course1_hours",          label: "Course 1 - Weekly Credit Hours" },
  { key: "course2_code",           label: "Course 2 - Code" },
  { key: "course2_name",           label: "Course 2 - Name" },
  { key: "course2_hours",          label: "Course 2 - Weekly Credit Hours" },
  { key: "course3_code",           label: "Course 3 - Code" },
  { key: "course3_name",           label: "Course 3 - Name" },
  { key: "course3_hours",          label: "Course 3 - Weekly Credit Hours" },
  { key: "publicationsFirstOrCorrespondingAuthor", label: "First/Corresponding Author Pubs" },
  { key: "publicationsQ1OrHighImpact",             label: "Q1 / IF>4.0 Pubs" },
  { key: "sciScopusCount",         label: "SCI/Scopus Count" },
  { key: "wosCount",               label: "WoS (SCIE/ESCI) Count" },
  { key: "conferencePapersCount",  label: "Conference Papers" },
  { key: "bookChaptersCount",      label: "Book Chapters" },
  { key: "reviewPublicationsCount",label: "Review Publications" },
  { key: "totalPublications",      label: "Total Publications (incl. co-authorship)" },
  { key: "totalCitations",         label: "Total Citations" },
  { key: "hIndex",                 label: "H-Index" },
  { key: "i10Index",               label: "i10-Index" },
  { key: "project1_title",         label: "Funded Project 1 - Title" },
  { key: "project1_agency",        label: "Funded Project 1 - Funding Agency" },
  { key: "project1_amount",        label: "Funded Project 1 - Grant Amount (₹L)" },
  { key: "project1_year",          label: "Funded Project 1 - Year" },
  { key: "project1_status",        label: "Funded Project 1 - Status" },
  { key: "project2_title",         label: "Funded Project 2 - Title" },
  { key: "project2_agency",        label: "Funded Project 2 - Funding Agency" },
  { key: "project2_amount",        label: "Funded Project 2 - Grant Amount (₹L)" },
  { key: "project2_year",          label: "Funded Project 2 - Year" },
  { key: "project2_status",        label: "Funded Project 2 - Status" },
  { key: "project3_title",         label: "Funded Project 3 - Title" },
  { key: "project3_agency",        label: "Funded Project 3 - Funding Agency" },
  { key: "project3_amount",        label: "Funded Project 3 - Grant Amount (₹L)" },
  { key: "project3_year",          label: "Funded Project 3 - Year" },
  { key: "project3_status",        label: "Funded Project 3 - Status" },
  { key: "consultancy1_title",     label: "Consultancy 1 - Title" },
  { key: "consultancy1_client",    label: "Consultancy 1 - Client/Agency" },
  { key: "consultancy1_revenue",   label: "Consultancy 1 - Revenue (₹L)" },
  { key: "consultancy1_year",      label: "Consultancy 1 - Year" },
  { key: "consultancy1_status",    label: "Consultancy 1 - Status" },
  { key: "consultancy2_title",     label: "Consultancy 2 - Title" },
  { key: "consultancy2_client",    label: "Consultancy 2 - Client/Agency" },
  { key: "consultancy2_revenue",   label: "Consultancy 2 - Revenue (₹L)" },
  { key: "consultancy2_year",      label: "Consultancy 2 - Year" },
  { key: "consultancy2_status",    label: "Consultancy 2 - Status" },
  { key: "consultancy3_title",     label: "Consultancy 3 - Title" },
  { key: "consultancy3_client",    label: "Consultancy 3 - Client/Agency" },
  { key: "consultancy3_revenue",   label: "Consultancy 3 - Revenue (₹L)" },
  { key: "consultancy3_year",      label: "Consultancy 3 - Year" },
  { key: "consultancy3_status",    label: "Consultancy 3 - Status" },
  { key: "patentIndianFiled",      label: "Patents - Indian Filed" },
  { key: "patentIndianPublished",  label: "Patents - Indian Published" },
  { key: "patentIndianGranted",    label: "Patents - Indian Granted" },
  { key: "patentInternationalFiled",     label: "Patents - International Filed" },
  { key: "patentInternationalPublished", label: "Patents - International Published" },
  { key: "patentInternationalGranted",   label: "Patents - International Granted" },
  { key: "patentDetails",          label: "Patents - Details" },
  { key: "phdScholarsPursuingCount",       label: "Ph.D. Scholars Pursuing - Count" },
  { key: "phdScholarsPursuingUniversities", label: "Ph.D. Scholars Pursuing - Universities" },
  { key: "phdScholarsAwardedCount",        label: "Ph.D. Scholars Awarded - Count" },
  { key: "phdScholarsAwardedUniversities", label: "Ph.D. Scholars Awarded - Universities" },
  { key: "nationalExposure",       label: "National Exposure (joint pubs w/ IITs/NITs/IIITs/CSIR)" },
  { key: "internationalExposure",  label: "International Exposure (joint pubs w/ foreign universities)" },
  { key: "lab1_details",           label: "New Lab 1 - Facility Details" },
  { key: "lab1_outcomes",          label: "New Lab 1 - Outcomes" },
  { key: "lab2_details",           label: "New Lab 2 - Facility Details" },
  { key: "lab2_outcomes",          label: "New Lab 2 - Outcomes" },
  { key: "lab3_details",           label: "New Lab 3 - Facility Details" },
  { key: "lab3_outcomes",          label: "New Lab 3 - Outcomes" },
  { key: "administrativeResponsibilities", label: "Administrative Responsibilities Held (+achievements)" },
  { key: "certificationsAndFdps",  label: "Certifications/FDPs (NPTEL/Coursera/AICTE)" },
  { key: "professionalBodyMemberships", label: "Professional Body Memberships (IEEE/ACM/CSI)" },
  { key: "book1_title",            label: "Authored Book 1 - Title" },
  { key: "book1_publisher",        label: "Authored Book 1 - Publisher" },
  { key: "book1_year",             label: "Authored Book 1 - Year" },
  { key: "book2_title",            label: "Authored Book 2 - Title" },
  { key: "book2_publisher",        label: "Authored Book 2 - Publisher" },
  { key: "book2_year",             label: "Authored Book 2 - Year" },
  { key: "book3_title",            label: "Authored Book 3 - Title" },
  { key: "book3_publisher",        label: "Authored Book 3 - Publisher" },
  { key: "book3_year",             label: "Authored Book 3 - Year" },
  { key: "notableAwards",          label: "Notable Awards" },

  // ─── Financial Standing & Budgetary Impact (Module 6) ───────────────────
  { key: "presentSalary",          label: "Present Salary (₹)" },
  { key: "grossAnnualCTC",         label: "Gross Annual CTC (₹)" },
  { key: "incrementsAwarded",      label: "Increments Awarded" },
  { key: "fundingConsultancyRevenue", label: "Funding/Consultancy Revenue Generation (₹)" },

  // ─── Others (Module 7) ───────────────────────────────────────────────────
  { key: "otherInformation",       label: "Other Information" },
];
