export function getOfferLetterHTML({
  candidateName,
  designation,
  department,
  joiningDate,
  ctcAnnual,
  ctcMonthly,
  subjects,
  collegeName,
  collegeAddress,
  letterDate,
}: {
  candidateName: string;
  designation: string;
  department: string;
  joiningDate: string;
  ctcAnnual: number;
  ctcMonthly: number;
  subjects?: string[];
  collegeName: string;
  collegeAddress?: string;
  letterDate: string;
}): string {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: "Times New Roman", serif; margin: 0; padding: 0; color: #000; }
  .page { width: 210mm; min-height: 297mm; padding: 20mm 25mm; box-sizing: border-box; }
  .header { text-align: center; border-bottom: 3px double #1d4ed8; padding-bottom: 16px; margin-bottom: 24px; }
  .college-name { font-size: 24px; font-weight: bold; color: #1d4ed8; margin: 0; }
  .college-address { font-size: 12px; color: #555; margin: 4px 0 0; }
  .title { text-align: center; font-size: 16px; font-weight: bold; text-decoration: underline; margin: 24px 0; letter-spacing: 1px; }
  .meta { margin-bottom: 20px; }
  .meta p { margin: 4px 0; font-size: 13px; }
  .body-text { font-size: 14px; line-height: 1.8; margin-bottom: 16px; }
  .terms-title { font-weight: bold; font-size: 14px; margin: 20px 0 8px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th { background: #1d4ed8; color: #fff; padding: 8px 12px; font-size: 13px; text-align: left; }
  td { padding: 8px 12px; font-size: 13px; border: 1px solid #ddd; }
  tr:nth-child(even) td { background: #f8fafc; }
  .signature { margin-top: 48px; display: flex; justify-content: space-between; }
  .sig-block { text-align: center; }
  .sig-line { width: 150px; border-top: 1px solid #000; margin: 48px auto 8px; }
  .footer { position: fixed; bottom: 10mm; left: 25mm; right: 25mm; font-size: 11px; color: #888; text-align: center; border-top: 1px solid #ddd; padding-top: 8px; }
</style>
</head>
<body>
<div class="page">
  <div class="header">
    <p class="college-name">${collegeName}</p>
    ${collegeAddress ? `<p class="college-address">${collegeAddress}</p>` : ""}
  </div>

  <div class="title">OFFER LETTER</div>

  <div class="meta">
    <p><strong>Date:</strong> ${letterDate}</p>
    <p><strong>Ref No:</strong> FMS/OL/${new Date().getFullYear()}/${Math.floor(Math.random() * 9000) + 1000}</p>
  </div>

  <p class="body-text">To,<br><strong>${candidateName}</strong></p>

  <p class="body-text">Dear ${candidateName},</p>

  <p class="body-text">
    We are pleased to offer you the position of <strong>${designation}</strong> in the Department of <strong>${department}</strong> at ${collegeName}, subject to satisfactory verification of your credentials and documents.
  </p>

  <p class="terms-title">Terms &amp; Conditions of Employment</p>
  <table>
    <tr><th>Detail</th><th>Information</th></tr>
    <tr><td>Designation</td><td>${designation}</td></tr>
    <tr><td>Department</td><td>${department}</td></tr>
    <tr><td>Date of Joining</td><td>${joiningDate}</td></tr>
    ${subjects?.length ? `<tr><td>Subjects to Teach</td><td>${subjects.join(", ")}</td></tr>` : ""}
    <tr><td>Monthly CTC</td><td>₹${ctcMonthly.toLocaleString("en-IN")} per month</td></tr>
    <tr><td>Annual CTC</td><td>₹${ctcAnnual.toLocaleString("en-IN")} per annum</td></tr>
  </table>

  <p class="body-text">
    This offer is contingent upon successful completion of background verification, original document verification, and joining formalities. Please report to the HR office on the date of joining with all original documents.
  </p>

  <p class="body-text">
    Kindly sign and return a copy of this letter as acceptance of the offer.
  </p>

  <div class="signature">
    <div class="sig-block">
      <div class="sig-line"></div>
      <p style="margin:0;font-size:13px;"><strong>Candidate Signature</strong></p>
      <p style="margin:4px 0 0;font-size:12px;color:#555;">${candidateName}</p>
    </div>
    <div class="sig-block">
      <div class="sig-line"></div>
      <p style="margin:0;font-size:13px;"><strong>Principal / Authorized Signatory</strong></p>
      <p style="margin:4px 0 0;font-size:12px;color:#555;">${collegeName}</p>
    </div>
  </div>
</div>

<div class="footer">
  ${collegeName} · Offer Letter · Generated by FMS on ${letterDate}
</div>
</body>
</html>`;
}

export function getAppointmentLetterHTML({
  candidateName,
  designation,
  department,
  joiningDate,
  collegeName,
  collegeAddress,
  letterDate,
}: {
  candidateName: string;
  designation: string;
  department: string;
  joiningDate: string;
  collegeName: string;
  collegeAddress?: string;
  letterDate: string;
}): string {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: "Times New Roman", serif; margin: 0; padding: 0; }
  .page { width: 210mm; min-height: 297mm; padding: 20mm 25mm; box-sizing: border-box; }
  .header { text-align: center; border-bottom: 3px double #1d4ed8; padding-bottom: 16px; margin-bottom: 24px; }
  .college-name { font-size: 24px; font-weight: bold; color: #1d4ed8; margin: 0; }
  .title { text-align: center; font-size: 16px; font-weight: bold; text-decoration: underline; margin: 24px 0; letter-spacing: 1px; }
  p { font-size: 14px; line-height: 1.8; margin: 12px 0; }
  .signature { margin-top: 48px; display: flex; justify-content: flex-end; }
  .sig-block { text-align: center; }
  .sig-line { width: 150px; border-top: 1px solid #000; margin: 48px auto 8px; }
</style>
</head>
<body>
<div class="page">
  <div class="header">
    <p class="college-name">${collegeName}</p>
    ${collegeAddress ? `<p style="font-size:12px;color:#555;margin:4px 0 0">${collegeAddress}</p>` : ""}
  </div>

  <div class="title">APPOINTMENT LETTER</div>

  <p>Date: ${letterDate}</p>
  <p>To,<br><strong>${candidateName}</strong></p>

  <p>Dear ${candidateName},</p>

  <p>
    With reference to your interview held recently, we are pleased to appoint you as <strong>${designation}</strong> in the Department of <strong>${department}</strong> at ${collegeName} with effect from <strong>${joiningDate}</strong>.
  </p>

  <p>Your appointment is subject to the following conditions:</p>
  <ol style="font-size:14px;line-height:1.8;">
    <li>This appointment is on a probationary basis initially for a period of one year.</li>
    <li>Your service is liable to be terminated without any notice during the probationary period if your performance is not found satisfactory.</li>
    <li>You will be governed by the service rules and regulations of the institution as amended from time to time.</li>
    <li>You shall not take up any other employment, business, or assignment without the prior written permission of the management.</li>
  </ol>

  <p>
    Please report to the HR department on <strong>${joiningDate}</strong> with all original documents for verification.
  </p>

  <p>We welcome you to our institution and wish you a successful career here.</p>

  <div class="signature">
    <div class="sig-block">
      <div class="sig-line"></div>
      <p style="margin:0;"><strong>Principal</strong></p>
      <p style="margin:4px 0 0;font-size:12px;color:#555;">${collegeName}</p>
    </div>
  </div>
</div>
</body>
</html>`;
}
