import type { LeaveTypeFull } from "@/types/leave";

export const LEAVE_TYPE_SEED: LeaveTypeFull[] = [
  {
    id: "CL",
    code: "CL",
    label: "Casual Leave",
    shortLabel: "CL",
    description: "Short-duration leave for personal or urgent matters. Holidays and Sundays within the period are not counted.",
    color: "blue",
    isActive: true,
    sortOrder: 1,
    rules: {
      daysPerYear: 12,
      accrualBasis: "annual_fixed",
      carryForwardCap: 0,
      maxPerApplication: 12,
      minPerApplication: 1,
      advanceNoticeDays: 1,
      retroactiveAllowed: false,
      excludeHolidaysAndSundays: true,
      encashPolicy: "never",
      requiresHandoverAfterDays: 5,
      approvalChain: "standard",
    },
  },
  {
    id: "SCL",
    code: "SCL",
    label: "Special Casual Leave",
    shortLabel: "SCL",
    description: "Granted to teaching staff for academic duties such as paper-setting, valuation camps, and Board assignments.",
    color: "purple",
    isActive: true,
    sortOrder: 2,
    rules: {
      daysPerYear: 10,
      accrualBasis: "annual_fixed",
      carryForwardCap: 0,
      maxPerApplication: 10,
      minPerApplication: 1,
      advanceNoticeDays: 0,
      retroactiveAllowed: true,
      excludeHolidaysAndSundays: true,
      eligibility: {
        isTeachingStaffOnly: true,
      },
      encashPolicy: "never",
      approvalChain: "standard",
    },
  },
  {
    id: "EL",
    code: "EL",
    label: "Earned Leave",
    shortLabel: "EL",
    description: "Accumulated earned leave. Vacation-staff earn 6 days per year; non-vacation staff earn 30 days. Holidays count within the period.",
    color: "green",
    isActive: true,
    sortOrder: 3,
    rules: {
      daysPerYear: 30,
      accrualBasis: "annual_fixed",
      carryForwardCap: 300,
      maxPerApplication: 120,
      minPerApplication: 3,
      advanceNoticeDays: 5,
      retroactiveAllowed: false,
      excludeHolidaysAndSundays: false,
      encashPolicy: "retirement_only",
      requiresHandoverAfterDays: 7,
      approvalChain: "standard",
      departmentOverrides: [
        { departmentName: "Dental", maxPerApplication: 30 },
      ],
    },
  },
  {
    id: "ML",
    code: "ML",
    label: "Sick Leave",
    shortLabel: "SL",
    description: "Half-pay leave for illness or injury. Accumulates 20 days per completed year of service, capped at 60 days. Medical certificate required for 3+ days.",
    color: "red",
    isActive: true,
    sortOrder: 4,
    rules: {
      accrualBasis: "per_completed_year",
      carryForwardCap: 60,
      maxPerApplication: 60,
      minPerApplication: 1,
      advanceNoticeDays: 0,
      retroactiveAllowed: true,
      excludeHolidaysAndSundays: false,
      certificateRequiredAfterDays: 3,
      fitnessCertRequired: true,
      eligibility: {
        employmentTypes: ["permanent"],
        isConfirmedRequired: true,
      },
      encashPolicy: "never",
      approvalChain: "standard",
    },
  },
  {
    id: "MAT",
    code: "MAT",
    label: "Maternity Leave",
    shortLabel: "MAT",
    description: "90 days maternity leave for permanent female employees. One-time grant; not available if 2 or more living children.",
    color: "pink",
    isActive: true,
    sortOrder: 5,
    rules: {
      daysPerYear: 90,
      accrualBasis: "none",
      maxPerApplication: 90,
      minPerApplication: 30,
      advanceNoticeDays: 0,
      retroactiveAllowed: true,
      excludeHolidaysAndSundays: false,
      eligibility: {
        employmentTypes: ["permanent"],
        genderAllowed: ["female"],
        maritalStatus: "married",
        minServiceYears: 1,
        maxLivingChildren: 1,
        oneTimeOnly: true,
      },
      requiresReturnToDutyAck: true,
      encashPolicy: "never",
      approvalChain: "standard",
    },
  },
  {
    id: "FPL",
    code: "FPL",
    label: "Family Planning Leave",
    shortLabel: "FPL",
    description: "Leave granted after family planning surgery: 6 days for male employees, 14 days for female employees.",
    color: "teal",
    isActive: true,
    sortOrder: 6,
    rules: {
      accrualBasis: "none",
      minPerApplication: 1,
      advanceNoticeDays: 0,
      retroactiveAllowed: true,
      excludeHolidaysAndSundays: false,
      certificateRequiredAfterDays: 0,
      eligibility: {
        employmentTypes: ["permanent"],
      },
      genderDayAllocation: { male: 6, female: 14, other: 14 },
      encashPolicy: "never",
      approvalChain: "standard",
    },
  },
  {
    id: "COMP",
    code: "COMP",
    label: "Compensatory Leave",
    shortLabel: "COMP",
    description: "Leave earned by working on a designated holiday. Must be linked to a recorded holiday-duty entry. Not available if remunerated for that day.",
    color: "amber",
    isActive: true,
    sortOrder: 7,
    rules: {
      daysPerYear: 5,
      accrualBasis: "annual_fixed",
      carryForwardCap: 0,
      maxPerApplication: 5,
      minPerApplication: 1,
      advanceNoticeDays: 1,
      retroactiveAllowed: false,
      excludeHolidaysAndSundays: true,
      linkedHolidayWorkRequired: true,
      remuneratedDutyBlocked: true,
      encashPolicy: "never",
      approvalChain: "standard",
    },
  },
  {
    id: "LND",
    code: "LND",
    label: "Leave Not Due",
    shortLabel: "LND",
    description: "An advance against future EL credit. Granted when EL balance is exhausted. Maximum 30 days; must be offset once EL is credited.",
    color: "orange",
    isActive: true,
    sortOrder: 8,
    rules: {
      accrualBasis: "none",
      maxPerApplication: 30,
      minPerApplication: 1,
      advanceNoticeDays: 1,
      retroactiveAllowed: false,
      excludeHolidaysAndSundays: false,
      isLeaveNotDue: true,
      eligibility: {
        employmentTypes: ["permanent"],
        isConfirmedRequired: true,
      },
      encashPolicy: "never",
      approvalChain: "standard",
    },
  },
  {
    id: "QUAR",
    code: "QUAR",
    label: "Quarantine Leave",
    shortLabel: "QUAR",
    description: "Leave ordered by a competent health authority due to infectious disease exposure. Medical certificate always required.",
    color: "cyan",
    isActive: true,
    sortOrder: 9,
    rules: {
      accrualBasis: "none",
      maxPerApplication: 21,
      minPerApplication: 1,
      advanceNoticeDays: 0,
      retroactiveAllowed: true,
      excludeHolidaysAndSundays: false,
      certificateRequiredAfterDays: 0,
      encashPolicy: "never",
      approvalChain: "standard",
    },
  },
  {
    id: "EOL",
    code: "EOL",
    label: "Extraordinary Leave",
    shortLabel: "EOL",
    description: "Leave without pay granted in exceptional circumstances when all other leave is exhausted.",
    color: "gray",
    isActive: true,
    sortOrder: 10,
    rules: {
      accrualBasis: "none",
      minPerApplication: 1,
      advanceNoticeDays: 3,
      retroactiveAllowed: false,
      excludeHolidaysAndSundays: false,
      isLeaveWithoutPay: true,
      encashPolicy: "never",
      approvalChain: "management",
      durationTiers: [
        {
          label: "Without Medical Certificate",
          maxDays: 90,
          requiresCertificate: false,
        },
        {
          label: "With Medical Certificate (min. 1 yr service)",
          maxDays: 180,
          requiresCertificate: true,
          minServiceYears: 1,
        },
        {
          label: "Higher Studies (min. 3 yrs service)",
          maxDays: 730,
          requiresCertificate: false,
          minServiceYears: 3,
          purpose: "higher_studies",
        },
      ],
    },
  },
  {
    id: "SAB",
    code: "SAB",
    label: "Sabbatical Leave",
    shortLabel: "SAB",
    description: "Extended leave for research, academic exchange, or professional development. Requires management approval.",
    color: "indigo",
    isActive: true,
    sortOrder: 11,
    rules: {
      accrualBasis: "none",
      minPerApplication: 1,
      advanceNoticeDays: 30,
      retroactiveAllowed: false,
      excludeHolidaysAndSundays: false,
      eligibility: {
        employmentTypes: ["permanent"],
        minServiceYears: 5,
      },
      encashPolicy: "never",
      approvalChain: "management",
    },
  },
  {
    id: "VAC",
    code: "VAC",
    label: "Vacation",
    shortLabel: "VAC",
    description: "Annual vacation entitlement for vacation-staff. Governed by institutional calendar; different from leave application.",
    color: "lime",
    isActive: true,
    sortOrder: 12,
    rules: {
      daysPerYear: 60,
      accrualBasis: "annual_fixed",
      carryForwardCap: 0,
      isVacationEntitlement: true,
      eligibility: {
        staffCategories: ["vacation"],
      },
      approvalChain: "standard",
    },
  },
];
