import {
  LayoutDashboard,
  Building2,
  Building,
  Users,
  ScrollText,
  ClipboardList,
  CalendarCheck,
  UserCheck,
  BarChart3,
  ClipboardPlus,
  Layers,
  Settings2,
  FolderOpen,
  UserCog,
  CalendarDays,
  MessageSquare,
  IndianRupee,
  FileText,
  Bell,
  LogOut,
  Menu,
  ChevronRight,
  CalendarClock,
  BookOpen,
  TrendingUp,
  GraduationCap,
  AlertCircle,
  Wallet,
  UsersRound,
  ClipboardCheck,
  MapPin,
  GitBranch,
  BookMarked,
  QrCode,
  PieChart,
  ShoppingCart,
  Receipt,
  UserPlus,
  type LucideProps,
} from "lucide-react";

const icons: Record<string, React.ComponentType<LucideProps>> = {
  LayoutDashboard,
  Building2,
  Building,
  Users,
  ScrollText,
  ClipboardList,
  CalendarCheck,
  UserCheck,
  BarChart3,
  ClipboardPlus,
  Layers,
  Settings2,
  FolderOpen,
  UserCog,
  CalendarDays,
  MessageSquare,
  IndianRupee,
  FileText,
  Bell,
  LogOut,
  Menu,
  ChevronRight,
  CalendarClock,
  BookOpen,
  TrendingUp,
  GraduationCap,
  AlertCircle,
  Wallet,
  UsersRound,
  ClipboardCheck,
  MapPin,
  GitBranch,
  BookMarked,
  QrCode,
  PieChart,
  ShoppingCart,
  Receipt,
  UserPlus,
};

export function NavIcon({ name, ...props }: { name: string } & LucideProps) {
  const Icon = icons[name] ?? LayoutDashboard;
  return <Icon {...props} />;
}
